### ISSUE TITLE
Please improve the readme

### ISSUE THREAD

**Issue by bonndan** [slidewiki/notification-service#2]
What is the service meant for? What does it do and what not? Is it ready for production? Sounds like a nice idea and is (and has been) certainly needed in companies... if it is what I think it is

Please add some more info to the readme. 

Thanks

**Comment by dpaun** [comment]
This service is meant for handling different kinds of notifications for users of SlideWiki Authoring platform for OpenCourseWare (see [slidewiki.eu](slidewiki.eu)).
It's still under development.
